

#pragma vertex VSMain
#pragma fragment PSMain
struct appdata
{
	float3 pos : POSITION;
	float4 col : COLOR0;
	float2 tex : TEXCOORD0;
};

struct v2p
{
	half4 pos : POSITION;
	half4 col : COLOR0;
	half2 tex : TEXCOORD0;
};

uniform float4x4 uMtxMVP;

v2p VSMain(appdata input)
{
	v2p output;
	output.pos = mul(uMtxMVP, float4(input.pos, 1.0));
	output.col = input.col;
	output.tex = input.tex;
	return output;
}

uniform sampler2D uMainTex;

half4 PSMain(v2p input) : COLOR0
{
	half4 col = tex2D(uMainTex, input.tex);
	return col * input.col;
}

