R"MW_SHADER_SOURCE(

#pragma vertex VSMain
#pragma fragment PSMain
struct appdata
{
	float3 pos : POSITION;
	float2 tex : TEXCOORD0;
};

struct v2p
{
	half4 pos : POSITION;
	half2 tex : TEXCOORD0;
};

uniform float4x4 uMtxMVP;

v2p VSMain(appdata input)
{
	v2p output;
	output.pos = mul(float4(input.pos, 1.0), uMtxMVP);
	output.tex = input.tex;
	return output;
}

uniform sampler2D uMainTex;

half4 PSMain(v2p input) : COLOR0
{
	return tex2D(uMainTex, input.tex);
}

)MW_SHADER_SOURCE"
